name: DevSecOps CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  scanning:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
      container:
        image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      - name: Run Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop-local juice-shop:latest

      - name: Wait for Juice Shop to be ready
        run: |
          sleep 60

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "http://juice-shop:3000"


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit (SCA)
        continue-on-error: true
        run: npm audit --audit-level=high

      - name: Run Semgrep (SAST)
        continue-on-error: true
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

      - name: Run Gitleaks (Secrets Scan)
        continue-on-error: true
        uses: gitleaks/gitleaks-action@v2